<Project Sdk="Godot.NET.Sdk/4.7.2">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
    <RootNamespace>InkodotEditor</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <InkodotStandaloneApp>true</InkodotStandaloneApp> <!-- controls Compiler shipment to release build -->
  </PropertyGroup>

  <Import Project="addons\ink\Ink.props" />

</Project>